const CV="https://cv-builder-xi-one.vercel.app/";const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
document.addEventListener("DOMContentLoaded",()=>{
$("#year").textContent=new Date().getFullYear();
if(localStorage.getItem("sh-theme")==="dark")document.body.classList.add("dark");$("#theme").textContent=document.body.classList.contains("dark")?"☀":"☾";
$("#theme").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("sh-theme",document.body.classList.contains("dark")?"dark":"light");$("#theme").textContent=document.body.classList.contains("dark")?"☀":"☾"};
$("#menu").onclick=()=>{$("#nav").style.display=$("#nav").style.display==="flex"?"":"flex";$("#nav").style.position="absolute";$("#nav").style.top="65px";$("#nav").style.left="12px";$("#nav").style.right="12px";$("#nav").style.padding="15px";$("#nav").style.background="var(--card)";$("#nav").style.border="1px solid var(--line)";$("#nav").style.borderRadius="16px";$("#nav").style.flexDirection="column";$("#nav").style.alignItems="stretch"};
$$("[data-cat]").forEach(b=>b.onclick=()=>{$$("[data-cat]").forEach(x=>x.classList.remove("active"));b.classList.add("active");filter()});
$("#search").oninput=filter;$$(".tool").forEach(x=>x.onclick=e=>{if(e.target.tagName==="BUTTON"||e.currentTarget===e.target)openTool(x.dataset.tool)});
$$("[data-cv]").forEach(x=>x.onclick=openCV);$("#modal").onclick=e=>{if(e.target.matches("[data-close]")||e.target.classList.contains("back"))closeTool()};$("#cvclose").onclick=closeCV;
document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeTool();closeCV()}});
});
function filter(){let cat=document.querySelector(".cats .active")?.dataset.cat||"all",q=$("#search").value.toLowerCase(),n=0;$$(".tool").forEach(x=>{let ok=(cat==="all"||x.dataset.cat.includes(cat))&&(!q||x.dataset.name.toLowerCase().includes(q)||x.textContent.toLowerCase().includes(q));x.classList.toggle("hidden",!ok);if(ok)n++});$("#none").classList.toggle("hidden",n>0)}
const T={
percentage:`<div class=form><div class=row><div class=field><label>Obtained marks</label><input id=a type=number placeholder=450></div><div class=field><label>Total marks</label><input id=b type=number placeholder=500></div></div><button class="btn primary" id=go>Calculate</button><div id=r></div></div>`,
gpa:`<div class=form><p class=muted>Enter credits and grade points (0–4).</p><div id=rows><div class=row><input class=c type=number placeholder=Credits><input class=g type=number step=.01 placeholder="Grade points"></div><div class=row><input class=c type=number placeholder=Credits><input class=g type=number step=.01 placeholder="Grade points"></div><div class=row><input class=c type=number placeholder=Credits><input class=g type=number step=.01 placeholder="Grade points"></div></div><button class="btn ghost" id=add>+ Add Course</button><button class="btn primary" id=go>Calculate GPA</button><div id=r></div></div>`,
cgpa:`<div class=form><p class=muted>Enter each semester GPA and credits.</p><div id=rows><div class=row><input class=g type=number step=.01 placeholder=GPA><input class=c type=number placeholder=Credits></div><div class=row><input class=g type=number step=.01 placeholder=GPA><input class=c type=number placeholder=Credits></div></div><button class="btn ghost" id=add>+ Add Semester</button><button class="btn primary" id=go>Calculate CGPA</button><div id=r></div></div>`,
grade:`<div class=form><div class=row><div class=field><label>Marks</label><input id=m type=number></div><div class=field><label>Total</label><input id=t type=number></div></div><button class="btn primary" id=go>Find Grade</button><div id=r></div><p class=muted>Scale: A+ ≥90, A ≥80, B ≥70, C ≥60, D ≥50, F &lt;50.</p></div>`,
attendance:`<div class=form><div class=row><div class=field><label>Classes attended</label><input id=a type=number></div><div class=field><label>Total classes</label><input id=t type=number></div></div><div class=field><label>Required attendance %</label><input id=req type=number value=75></div><button class="btn primary" id=go>Calculate</button><div id=r></div></div>`,
average:`<div class=form><div class=field><label>Numbers separated by commas</label><input id=n placeholder="10, 20, 30, 40"></div><button class="btn primary" id=go>Calculate Average</button><div id=r></div></div>`,
age:`<div class=form><div class=field><label>Date of birth</label><input id=d type=date></div><button class="btn primary" id=go>Calculate Age</button><div id=r></div></div>`,
units:`<div class=form><div class=row><input id=v type=number placeholder=10><select id=type><option value=length>Length</option><option value=weight>Weight</option><option value=temp>Temperature</option><option value=data>Data</option></select></div><div class=row><select id=from></select><select id=to></select></div><button class="btn primary" id=go>Convert</button><div id=r></div></div>`,
words:`<div class=form><textarea id=text rows=9 placeholder="Paste your assignment here..."></textarea><div class=wordstats><div><b id=w>0</b><small>Words</small></div><div><b id=ch>0</b><small>Characters</small></div><div><b id=se>0</b><small>Sentences</small></div><div><b id=rt>0</b><small>Minutes</small></div></div></div>`,
case:`<div class=form><textarea id=text rows=9 placeholder="Type or paste text..."></textarea><div class=row><button class="btn ghost" data-case=upper>UPPERCASE</button><button class="btn ghost" data-case=lower>lowercase</button></div><div class=row><button class="btn ghost" data-case=title>Title Case</button><button class="btn ghost" data-case=sentence>Sentence case</button></div></div>`,
timer:`<div class=form><div class=timer id=tm>25:00</div><div class=timerbuttons><button class="btn primary" id=start>Start</button><button class="btn ghost" id=reset>Reset</button></div><p class=muted style="text-align:center">25-minute focus session.</p></div>`,
countdown:`<div class=form><div class=field><label>Exam date & time</label><input id=date type=datetime-local></div><button class="btn primary" id=go>Start Countdown</button><div id=r></div></div>`,
qr:`<div class=form><div class=field><label>Text or URL</label><input id=q placeholder="https://example.com"></div><button class="btn primary" id=go>Generate QR</button><div id=r></div><p class=muted>Uses a public QR image service; do not put private information into the QR text.</p></div>`,
password:`<div class=form><div class=field><label>Length</label><input id=len type=number value=16 min=8 max=64></div><button class="btn primary" id=go>Generate Password</button><div id=r></div></div>`,
planner:`<div class=form><div class=row><input id=task placeholder="Study task"><button class="btn primary" id=add>Add</button></div><div class=planner-list id=list></div><button class="btn ghost" id=clear>Clear All</button></div>`,
cv:`<div class=form><p class=muted>Open the official CV Builder connected to StudentHub.</p><button class="btn primary" id=go>Open Official CV Builder →</button></div>`
};
const names={percentage:"Percentage Calculator",gpa:"GPA Calculator",cgpa:"CGPA Calculator",grade:"Grade Calculator",attendance:"Attendance Calculator",average:"Average Calculator",age:"Age Calculator",units:"Unit Converter",words:"Word Counter",case:"Case Converter",timer:"Study Timer",countdown:"Exam Countdown",qr:"QR Code Generator",password:"Password Generator",planner:"Study Planner",cv:"CV Builder"};
function openTool(type){$("#modal").classList.add("open");$("#title").textContent=names[type];$("#kicker").textContent=type==="cv"?"OFFICIAL":"STUDENT TOOL";$("#body").innerHTML=T[type];init(type)}
function closeTool(){$("#modal").classList.remove("open")}
function init(x){
if(x==="percentage")$("#go").onclick=()=>{let a=+$("#a").value,b=+$("#b").value;$("#r").innerHTML=b?`<div class=result><strong>${(a/b*100).toFixed(2)}%</strong><br>Percentage</div>`:"Enter valid marks."};
if(x==="gpa"){ $("#add").onclick=()=>$("#rows").insertAdjacentHTML("beforeend",`<div class=row><input class=c type=number placeholder=Credits><input class=g type=number step=.01 placeholder="Grade points"></div>`);$("#go").onclick=()=>{let p=0,c=0;$$(".c").forEach((e,i)=>{let cr=+e.value,g=+$(".g")[i].value;if(cr>0){p+=cr*g;c+=cr}});$("#r").innerHTML=c?`<div class=result><strong>${(p/c).toFixed(2)}</strong><br>Weighted GPA</div>`:"Enter valid data."}};
if(x==="cgpa"){ $("#add").onclick=()=>$("#rows").insertAdjacentHTML("beforeend",`<div class=row><input class=g type=number step=.01 placeholder=GPA><input class=c type=number placeholder=Credits></div>`);$("#go").onclick=()=>{let p=0,c=0;$$(".g").forEach((e,i)=>{let g=+e.value,cr=+$(".c")[i].value;if(cr>0){p+=g*cr;c+=cr}});$("#r").innerHTML=c?`<div class=result><strong>${(p/c).toFixed(2)}</strong><br>Weighted CGPA</div>`:"Enter valid data."}};
if(x==="grade")$("#go").onclick=()=>{let m=+$("#m").value,t=+$("#t").value,p=t?m/t*100:0,g=p>=90?"A+":p>=80?"A":p>=70?"B":p>=60?"C":p>=50?"D":"F";$("#r").innerHTML=t?`<div class=result><strong>${g}</strong><br>${p.toFixed(2)}%</div>`:"Enter valid marks."};
if(x==="attendance")$("#go").onclick=()=>{let a=+$("#a").value,t=+$("#t").value,req=+$("#req").value||75,p=t?a/t*100:0;let extra=Math.max(0,Math.ceil((req*t/100-a)/(1-req/100)));$("#r").innerHTML=t?`<div class=result><strong>${p.toFixed(2)}%</strong><br>${p>=req?`You can currently miss up to ${Math.floor((a/100*100-req*t/100)/(req/100))} class(es) approximately.`:`You need to attend the next ${extra} class(es) consecutively to reach ${req}%.`}</div>`:"Enter valid data."};
if(x==="average")$("#go").onclick=()=>{let n=$("#n").value.split(",").map(Number).filter(Number.isFinite);$("#r").innerHTML=n.length?`<div class=result><strong>${(n.reduce((a,b)=>a+b,0)/n.length).toFixed(2)}</strong><br>Total: ${n.reduce((a,b)=>a+b,0)} · Highest: ${Math.max(...n)} · Lowest: ${Math.min(...n)}</div>`:"Enter comma-separated numbers."};
if(x==="age")$("#go").onclick=()=>{let d=new Date($("#d").value),now=new Date();if(isNaN(d))return;let y=now.getFullYear()-d.getFullYear(),m=now.getMonth()-d.getMonth(),day=now.getDate()-d.getDate();if(day<0){m--;day+=new Date(now.getFullYear(),now.getMonth(),0).getDate()}if(m<0){y--;m+=12}$("#r").innerHTML=`<div class=result><strong>${y} years, ${m} months, ${day} days</strong></div>`};
if(x==="units"){let U={length:{m:["Meter",1],km:["Kilometer",1000],cm:["Centimeter",.01],ft:["Foot",.3048],in:["Inch",.0254]},weight:{kg:["Kilogram",1],g:["Gram",.001],lb:["Pound",.45359237],oz:["Ounce",.0283495]},data:{B:["Bytes",1],KB:["KB",1024],MB:["MB",1048576],GB:["GB",1073741824]},temp:{C:["Celsius",0],F:["Fahrenheit",0],K:["Kelvin",0]}};function set(){let u=U[$("#type").value];$("#from").innerHTML=Object.entries(u).map(([k,v])=>`<option value=${k}>${v[0]}</option>`).join("");$("#to").innerHTML=Object.entries(u).map(([k,v])=>`<option value=${k}>${v[0]}</option>`).join("")}$("#type").onchange=set;set();$("#go").onclick=()=>{let typ=$("#type").value,v=+$("#v").value,f=$("#from").value,t=$("#to").value,o=v;if(typ==="temp"){let c=f==="C"?v:f==="F"?(v-32)*5/9:v-273.15;o=t==="C"?c:t==="F"?c*9/5+32:c+273.15}else o=v*U[typ][f][1]/U[typ][t][1];$("#r").innerHTML=`<div class=result><strong>${Number(o.toFixed(6))}</strong> ${U[typ][t][0]}</div>`}};
if(x==="words")$("#text").oninput=()=>{let t=$("#text").value,w=t.trim()?t.trim().split(/\s+/).length:0;$("#w").textContent=w;$("#ch").textContent=t.length;$("#se").textContent=t.split(/[.!?]+/).filter(a=>a.trim()).length;$("#rt").textContent=Math.ceil(w/200)};
if(x==="case")$$("[data-case]").forEach(b=>b.onclick=()=>{let t=$("#text").value,c=b.dataset.case;if(c==="upper")t=t.toUpperCase();if(c==="lower")t=t.toLowerCase();if(c==="title")t=t.toLowerCase().replace(/\b\w/g,a=>a.toUpperCase());if(c==="sentence")t=t.toLowerCase().replace(/(^\s*\w|[.!?]\s+\w)/g,a=>a.toUpperCase());$("#text").value=t});
if(x==="timer"){let s=1500,i;function render(){$("#tm").textContent=`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`}$("#start").onclick=()=>{if(i){clearInterval(i);i=null;$("#start").textContent="Start"}else{i=setInterval(()=>{if(s<=0){clearInterval(i);i=null;$("#start").textContent="Start";return}s--;render()},1000);$("#start").textContent="Pause"}};$("#reset").onclick=()=>{clearInterval(i);i=null;s=1500;render();$("#start").textContent="Start"}}
if(x==="countdown")$("#go").onclick=()=>{let d=new Date($("#date").value);if(isNaN(d))return;let box=$("#r");clearInterval(window.cd);let run=()=>{let ms=d-new Date();if(ms<=0){box.innerHTML=`<div class=result><strong>Exam time!</strong></div>`;clearInterval(window.cd);return}let days=Math.floor(ms/864e5),h=Math.floor(ms%864e5/36e5),m=Math.floor(ms%36e5/6e4),s=Math.floor(ms%6e4/1e3);box.innerHTML=`<div class=result><strong>${days}d ${h}h ${m}m ${s}s</strong><br>remaining</div>`};run();window.cd=setInterval(run,1000)};
if(x==="qr")$("#go").onclick=()=>{let v=$("#q").value;if(!v)return;$("#r").innerHTML=`<div class=result style="text-align:center"><img alt="QR code" style="max-width:220px;border-radius:12px" src="https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${encodeURIComponent(v)}"><p>QR generated for the entered text.</p></div>`};
if(x==="password")$("#go").onclick=()=>{let n=Math.min(64,Math.max(8,+$("#len").value||16)),chars="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%^&*";let a=new Uint32Array(n);crypto.getRandomValues(a);let p=[...a].map(v=>chars[v%chars.length]).join("");$("#r").innerHTML=`<div class=result><input value="${p}" readonly style="width:100%;padding:10px;background:var(--soft);color:var(--text);border:1px solid var(--line);border-radius:9px"><p class=muted>Generated locally in your browser.</p></div>`};
if(x==="planner"){let key="sh-planner";function load(){let a=JSON.parse(localStorage.getItem(key)||"[]");$("#list").innerHTML=a.map((t,i)=>`<div class=task><input type=checkbox ${t.done?"checked":""} data-i=${i}><span style="${t.done?"text-decoration:line-through;opacity:.55":""}">${esc(t.text)}</span><button data-del=${i}>×</button></div>`).join("");$$("[data-i]").forEach(c=>c.onchange=()=>{a[c.dataset.i].done=c.checked;localStorage.setItem(key,JSON.stringify(a));load()});$$("[data-del]").forEach(b=>b.onclick=()=>{a.splice(b.dataset.del,1);localStorage.setItem(key,JSON.stringify(a));load()})}$("#add").onclick=()=>{let t=$("#task").value.trim();if(!t)return;let a=JSON.parse(localStorage.getItem(key)||"[]");a.push({text:t,done:false});localStorage.setItem(key,JSON.stringify(a));$("#task").value="";load()};$("#clear").onclick=()=>{localStorage.removeItem(key);load()};load()}
if(x==="cv")$("#go").onclick=openCV}
function esc(s){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function openCV(){$("#cvmodal").classList.add("open");$("#loading").classList.add("show");$("#fallback").classList.remove("show");$("#cvframe").src=CV;let ok=false;$("#cvframe").onload=()=>{ok=true;setTimeout(()=>$("#loading").classList.remove("show"),500)};setTimeout(()=>{if(!ok){$("#loading").classList.remove("show");$("#fallback").classList.add("show")}},5000)}
function closeCV(){$("#cvmodal").classList.remove("open");setTimeout(()=>$("#cvframe").src="about:blank",200)}
